name:                mdium
version:             1.0.0
homepage:            https://github.com/matsubara0507/mdium#readme
license:             MIT
author:              MATSUBARA Nobutada
maintainer:          t12307043@gunma-u.ac.jp
copyright:           MATSUBARA Nobutada
category:            Web
description:         Please see the README on GitHub at <https://github.com/matsubara0507/mdium#readme>

extra-source-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -optP-Wno-nonportable-include-path

default-extensions:
- NoImplicitPrelude

- ConstraintKinds
- DataKinds
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedLabels
- OverloadedStrings
- PolyKinds
- RankNTypes
- StandaloneDeriving
- TypeFamilies
- TypeOperators
- TypeSynonymInstances

dependencies:
- base >= 4.7 && < 5
- rio >= 0.1.1.0
- aeson
- extensible >= 0.6
- fallible
- mix
- mix-json-logger
- wreq

library:
  source-dirs: src

executables:
  mdium:
    main: Main.hs
    source-dirs: app
    dependencies:
    - mdium
    - githash
    - dotenv
