resolver: lts-12.16
packages:
- .
extra-deps:
- dotenv-0.6.0.3
- megaparsec-7.0.3

docker:
  repo: fpco/stack-build
  enable: false
image:
  container:
    name: matsubara0507/mdium
    base: fpco/ubuntu-with-libgmp
