resolver: lts-20.11
packages:
- .
extra-deps:
- extensible-0.9
- membership-0.0.1
- fallible-0.1.0
- incremental-0.3.1

- github: matsubara0507/mix.hs
  commit: 9bcd386526fe10a025a23e951c2de86b05129b17
  subdirs:
  - mix
  - mix-json-logger
  - mix-plugin-github

docker:
  repo: matsubara0507/stack-build
  enable: false
