resolver: lts-18.21
packages:
- .
extra-deps:
- extensible-0.8.2
- membership-0.0.1
- fallible-0.1.0
- incremental-0.3.1
- binary-instances-1.0.2

- github: matsubara0507/mix.hs
  commit: 75714be080db16f6a4f9d0a22e86947ffcdadc57
  subdirs:
  - mix
  - mix-json-logger
  - mix-plugin-github
- github: phadej/github
  commit: 81d9b658c33a706f18418211a78d2690752518a4

docker:
  repo: matsubara0507/stack-build
  enable: false
