resolver: lts-16.23
packages:
- .
extra-deps:
- extensible-0.8.1
- membership-0
- fallible-0.1.0
- incremental-0.3.1
- pandoc-2.11.3.2
- citeproc-0.3.0.3
- commonmark-0.1.1.2
- commonmark-extensions-0.2.0.4
- commonmark-pandoc-0.2.0.1
- pandoc-types-1.22
- rfc5051-0.2
- doctemplates-0.9
- hslua-1.3.0
- jira-wiki-markup-1.3.2
- skylighting-0.10.2
- skylighting-core-0.10.2
- texmath-0.12.1
- hslua-module-system-0.2.2.1
- hslua-module-text-0.3.0.1
- binary-instances-1.0.1
- github: matsubara0507/mix.hs
  commit: 75714be080db16f6a4f9d0a22e86947ffcdadc57
  subdirs:
  - mix
  - mix-json-logger
  - mix-plugin-github
- github: matsubara0507/github
  commit: c44824bb6c41aad7fc9ac59e4686e138c9d67066

docker:
  repo: matsubara0507/stack-build
  enable: false
