resolver: lts-14.6
packages:
- .
extra-deps:
- dotenv-0.8.0.2
- megaparsec-7.0.5
- extensible-0.6.1
- membership-0
- github: matsubara0507/fallible
  commit: dfbdce1a0b0c71bcfcea844c94f9cb815f071235
- github: matsubara0507/mix.hs
  commit: 4978a33dec736799b30c14e215f7fa0f29fa2884
  subdirs:
  - mix
  - mix-json-logger

docker:
  repo: matsubara0507/stack-build
  enable: false
