resolver: lts-16.13
packages:
- .
extra-deps:
- extensible-0.8
- membership-0
- fallible-0.1.0
- github: matsubara0507/mix.hs
  commit: 75714be080db16f6a4f9d0a22e86947ffcdadc57
  subdirs:
  - mix
  - mix-json-logger

docker:
  repo: matsubara0507/stack-build
  enable: false
