name: Build Application

on:
  pull_request: null
  push:
    branches:
    - master

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        ghc: ["9.2.5"]

    steps:
    - uses: actions/checkout@v2
    - name: inistall libtinfo5 for GHC on Bazel
      run: |
        sudo apt-get update
        sudo apt-get install -y libtinfo5

    - name: Cache Bazel
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/bazel
        key: ${{ runner.os }}-${{ hashFiles('WORKSPACE') }}

    - name: Build binary
      run: |
        bazelisk build //:mdium
        bazel-bin/mdium --version
        bazel-bin/mdium --help

    - name: Build image
      run: bazelisk build //:image

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: matsubara0507
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push image
      if: ${{ github.event_name != 'pull_request' }}
      run: bazelisk run //:push
