name: Build Application

on:
  pull_request: null
  push:
    branches:
    - master

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.8.4"]

    steps:
    - uses: actions/checkout@v2

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v1.1.2
      with:
        path: ~/.stack
        key: "\
          ${{ runner.os }}-stack\
          -${{ hashFiles('**/stack.yaml.lock') }}\
          -${{ hashFiles('**/package.yaml') }}\
        "
        restore-keys: |
          ${{ runner.os }}-stack-
    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: 'latest'

    - name: Install dependencies
      run: stack --system-ghc test --only-dependencies

    - name: Build and Test
      run: stack --system-ghc test --local-bin-path=./bin

    # Build and Push Docker Image
    - name: Prepare
      id: prep
      run: |
        DOCKER_IMAGE=ghcr.io/matsubara0507/mdium
        TAGS="${DOCKER_IMAGE}:latest"
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          TAGS="$TAGS,${DOCKER_IMAGE}:${GITHUB_REF#refs/tags/v}"
        fi
        echo ::set-output name=tags::${TAGS}

    - name: Setup QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all

    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
      with:
        version: latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: matsubara0507
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        builder: ${{ steps.buildx.outputs.name }}
        platforms: linux/amd64,linux/arm64,linux/386
        tags: ${{ steps.prep.outputs.tags }}
        push: ${{ github.event_name != 'pull_request' }}
        build-args: local_bin_path=./bin
